# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.cache/wt [current_project]
set_property parent.project_path Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/sources_1/imports/lab_3/divider.v
  Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/sources_1/imports/lab_3/Timer.v
  Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/sources_1/imports/lab_3/FSM.v
  Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/sources_1/imports/lab_3/LEDController.v
  Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/sources_1/imports/lab_3/TrafficController.v
}
read_xdc Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/constrs_1/imports/EE_460M_lab/Basys3_Master.xdc
set_property used_in_implementation false [get_files Z:/__SchoolWork/EE_460M_lab/lab_3/lab_3_xilinx_project/lab_3_xilinx_project.srcs/constrs_1/imports/EE_460M_lab/Basys3_Master.xdc]

catch { write_hwdef -file TrafficController.hwdef }
synth_design -top TrafficController -part xc7a35tcpg236-2
write_checkpoint -noxdef TrafficController.dcp
catch { report_utilization -file TrafficController_utilization_synth.rpt -pb TrafficController_utilization_synth.pb }
