# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/EE460M/Lab7_partA_lights/Lab7_partA_lights.cache/wt [current_project]
set_property parent.project_path Z:/EE460M/Lab7_partA_lights/Lab7_partA_lights.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  Z:/EE460M/Lab7_partA_lights/Lab7_partA_lights.srcs/sources_1/imports/Downloads/Divider.v
  Z:/EE460M/Lab7_partA_lights/Lab7_partA_lights.srcs/sources_1/imports/Downloads/lab7_lights.v
}
read_xdc Z:/EE460M/Lab7_partA_lights/Lab7_partA_lights.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files Z:/EE460M/Lab7_partA_lights/Lab7_partA_lights.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]

catch { write_hwdef -file Complete_MIPS.hwdef }
synth_design -top Complete_MIPS -part xc7a35tcpg236-1
write_checkpoint -noxdef Complete_MIPS.dcp
catch { report_utilization -file Complete_MIPS_utilization_synth.rpt -pb Complete_MIPS_utilization_synth.pb }
