# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-2L
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.cache/wt [current_project]
set_property parent.project_path Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/DisplayFSM.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/BCDTo7Segment.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/Divider.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/SevenSegmentDisplayController.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/BinaryToBCD4.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/TimeLeft.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/debouncer_singlepulser.v
  Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/sources_1/imports/lab_4/ParkingMeter.v
}
read_xdc Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/constrs_1/imports/lab_4/Basys3_Master.xdc
set_property used_in_implementation false [get_files Z:/__SchoolWork/EE_460M_lab/lab_4/lab_4_xilinx_project/lab_4_xilinx_project.srcs/constrs_1/imports/lab_4/Basys3_Master.xdc]

catch { write_hwdef -file ParkingMeter.hwdef }
synth_design -top ParkingMeter -part xc7a35tcpg236-2L
write_checkpoint -noxdef ParkingMeter.dcp
catch { report_utilization -file ParkingMeter_utilization_synth.rpt -pb ParkingMeter_utilization_synth.pb }
