
-- This file has been automatically generated by SimUAid.

library ieee;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

library SimUAid_synthesis;
use SimUAid_synthesis.SimuAid_synthesis_pack.all;

entity EE316_lab2_circuit_vhdl is
port(A, B, C, D, E: in STD_LOGIC;

	W, X, Y, Z: out STD_LOGIC
	);
end EE316_lab2_circuit_vhdl;

architecture Structure of EE316_lab2_circuit_vhdl is
	signal A_p, B_p, D_p, Vnet_0, Vnet_1, Vnet_2, Vnet_3, Vnet_4, Vnet_5, Vnet_6, 
		Vnet_7, Vnet_8, Vnet_9, Vnet_10, Vnet_11, Vnet_12, Vnet_13, Vnet_14, E_p, Vnet_15, 
		Vnet_16, Vnet_17, Vnet_18, Vnet_19, Vnet_20, Vnet_21, Vnet_22: STD_LOGIC;
begin
	VHDL_Device_0: inverter port map (A, A_p);
	VHDL_Device_1: inverter port map (B, B_p);
	VHDL_Device_2: inverter port map (D, D_p);
	VHDL_Device_3: inverter port map (E, E_p);
	VHDL_Device_4: nor3 port map (A, B, C, Vnet_0);
	VHDL_Device_5: nor3 port map (A, C, E, Vnet_1);
	VHDL_Device_6: nor3 port map (A_p, C, E, Vnet_2);
	VHDL_Device_7: nor3 port map (B_p, C, E_p, Vnet_4);
	VHDL_Device_8: nor3 port map (A, B, D, Vnet_11);
	VHDL_Device_9: nor3 port map (C, D, E, Vnet_12);
	VHDL_Device_10: nor3 port map (A_p, B_p, D, Vnet_14);
	VHDL_Device_11: nor3 port map (A, B, E, Vnet_6);
	VHDL_Device_12: nor3 port map (A_p, C, D, Vnet_7);
	VHDL_Device_13: nor3 port map (A, D, E, Vnet_8);
	VHDL_Device_14: nor4 port map (B_p, C, D_p, E_p, Vnet_5);
	VHDL_Device_15: nor4 port map (Vnet_0, Vnet_1, Vnet_10, Vnet_9, W);
	VHDL_Device_16: nor4 port map (Vnet_10, Vnet_3, Vnet_15, Vnet_8, Z);
	VHDL_Device_17: nor5 port map (Vnet_2, Vnet_4, Vnet_11, Vnet_12, Vnet_10, X);
	VHDL_Device_18: nor5 port map (Vnet_14, Vnet_5, Vnet_6, Vnet_7, Vnet_8, Y);
	VHDL_Device_19: nor2 port map (A_p, B_p, Vnet_10);
	VHDL_Device_20: nor2 port map (C, D, Vnet_9);
	VHDL_Device_21: nor2 port map (C, E, Vnet_3);
	VHDL_Device_22: nor2 port map (A, B, Vnet_15);
end Structure;