
-- This file has been automatically generated by SimUAid.

library ieee;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

library SimUAid_synthesis_Package;
use SimUAid_synthesis_Package.SimuAid_synthesis_pack.all;

entity SM is
port(X, clk, rst, SET: in STD_LOGIC;

	Z, Q1, Q2, Q3: out STD_LOGIC
	);
end SM;

architecture Structure of SM is
	signal D1, SET_p, RESET_p, Vnet_0, Vnet_1, Vnet_2, Vnet_3, Q1_p, D2, Vnet_4, 
		Q2_p, D3, Q3_p, X_p: STD_LOGIC;
begin
	VHDL_Device_0: Dflipflop port map (clk, D1, SET_p, rst, Vnet_0, Q1_p);
	VHDL_Device_1: Dflipflop port map (clk, D2, SET_p, rst, Vnet_4, Q2_p);
	VHDL_Device_2: Dflipflop port map (clk, D3, SET_p, rst, Q3, Q3_p);
	VHDL_Device_3: inverter port map (X, X_p);
--	VHDL_Device_4: inverter port map (rst, RESET_p);

	VHDL_Device_5: or2 port map (X_p, Vnet_1, D1);
	VHDL_Device_6: and3 port map (Vnet_0, Vnet_4, Q3_p, Vnet_1);
	VHDL_Device_7: or3 port map (X, Vnet_0, Vnet_4, D2);
	VHDL_Device_8: and2 port map (X, Q2_p, Vnet_2);
	VHDL_Device_9: and2 port map (Q1_p, Vnet_4, Vnet_3);
	VHDL_Device_10: or2 port map (Vnet_2, Vnet_3, D3);
	VHDL_Device_11: and4 port map (X_p, Q1_p, Vnet_4, Q3_p, Z);
	VHDL_Device_12: inverter port map (SET, SET_p);
	Q1 <= Vnet_0;
	Q2 <= Vnet_4;
end Structure;