# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-2L
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.cache/wt [current_project]
set_property parent.project_path Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/Divider.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/HexTo7Segment.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/DisplayFSM.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/ShiftReg.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/ChangeCode.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/Strobe.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/SevenSegmentDisplayController.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/CodeReg.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/KeyToCommand.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/VGADisplayController.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/GameState.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/partA.v
  Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/sources_1/imports/lab_5_part_C_with_KB/SnakeKB.v
}
read_xdc Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/constrs_1/imports/EE_460M_lab/Basys3_Master.xdc
set_property used_in_implementation false [get_files Z:/__SchoolWork/EE_460M_lab/lab_5_part_C_with_KB/SnakeKB/SnakeKB.srcs/constrs_1/imports/EE_460M_lab/Basys3_Master.xdc]

catch { write_hwdef -file SnakeKB.hwdef }
synth_design -top SnakeKB -part xc7a35tcpg236-2L
write_checkpoint -noxdef SnakeKB.dcp
catch { report_utilization -file SnakeKB_utilization_synth.rpt -pb SnakeKB_utilization_synth.pb }
